name: artathens

on:
  schedule:
    - cron: '0 */12 * * *'
  

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

       
      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "Update"
     
      
      - name: grab m3u files
        run: |
            pwd
            cd ./core/platforms/
            pip3 install beautifulsoup4
            python3 artathens.py
      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git commit -m "streams updated"
          git push
