name: grabbing streams

on:
  schedule:
    - cron: '0 */4 * * *'
  
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

       
      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "Update"
      
      
      - name: grab m3u files
        run: |
            pwd
            cd ./core/platforms/
            python3 twitch.py diabatatv > ../../streams/diabatatv.m3u8
            python3 twitch.py astratv2021 > ../../streams/Astra_TV.m3u8
            python3 twitch.py astratv2019 > ../../streams/Astra_TV_bup.m3u8
            python3 twitch.py dtpylias > ../../streams/DTP.m3u8
            python3 twitch.py diontvkmakedonias > ../../streams/DionTvKentrikisMakedonias.m3u8
            python3 twitch.py eurotvgr > ../../streams/EuroTV.m3u8
            python3 dailymotion.py x2j7kha > ../../streams/Euronews_Greece.m3u8
            python3 twitch.py flashtvgr > ../../streams/FlashTV.m3u8
            python3 twitch.py kostv2024 > ../../streams/Kardamena_TV.m3u8
            python3 twitch.py lepantotv > ../../streams/LePanto.m3u8
            python3 twitch.py marontvgr > ../../streams/marontvgr.m3u8
            python3 twitch.py ontv2023 > ../../streams/On_Tv_Greece.m3u8
            python3 twitch.py orthodoxiaradio > ../../streams/Orthodoxia_Radio_TV.m3u8          
            python3 twitch.py pronewstv > ../../streams/ProNews.m3u8
            python3 dailymotion.py k5Hfx6eeaTjBE5zRXcn > ../../streams/Star_Kentrikis_Eladas_Greece.m3u8
            python3 twitch.py tvkosmosgr > ../../streams/tvkosmosgr.m3u8
            python3 twitch.py tvrodopi > ../../streams/TVRodopi.m3u8
            python3 twitch.py topchannelkozani > ../../streams/Top_Channel_Greece.m3u8
            python3 twitch.py xtvision > ../../streams/XTV.m3u8
            python3 twitch.py centertv > ../../streams/centertv.m3u8
            python3 twitch.py livethess > ../../streams/thessaliatv.m3u8
            python3 twitch.py tvstarfm > ../../streams/tvstarfm.m3u8
            python3 twitch.py verginacy > ../../streams/verginatv_cyprus.m3u8
            python3 twitch.py iviewtvgr > ../../streams/iviewtvgr.m3u8
            python3 twitch.py xylagany_paradosi > ../../streams/xylagany_paradosi.m3u8
            python3 twitch.py superstarfm > ../../streams/superstarfm.m3u8
            python3 twitch.py alithiavideo > ../../streams/alithiatv.m3u8
            python3 twitch.py hotbeatstv > ../../streams/hotbeatstv.m3u8
      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git commit -m "streams updated"
          git push
