name: grabbing streams

on:
  schedule:
    - cron: '0 */2 * * *'
  
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

       
      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "Update"
      
      
      - name: grab m3u files
        run: |
            pwd
            cd ./core/platforms/
            python3 twitch.py konitsaplustv > ../../streams/konitsaplustv.m3u8
            python3 twitch.py tvxalastra > ../../streams/xalastratv.m3u8
            python3 twitch.py pakoestream > ../../streams/pakoe.m3u8
            python3 twitch.py fatsabooktv > ../../streams/fatsabooktv.m3u8
            python3 twitch.py diavata_tv > ../../streams/diabatatv.m3u8
            python3 twitch.py aktinaradio > ../../streams/aktinaradio.m3u8
            python3 twitch.py astratv2021 > ../../streams/Astra_TV.m3u8
            python3 twitch.py astratv2019 > ../../streams/Astra_TV_bup.m3u8
            python3 twitch.py dtpylias > ../../streams/DTP.m3u8
            python3 dailymotion.py x2j7kha > ../../streams/Euronews_Greece.m3u8
            python3 dailymotion.py k5Hfx6eeaTjBE5zRXcn > ../../streams/starkebup.m3u8
            python3 dailymotion.py 1ilp5b3jja3168a4092 > ../../streams/starkebup2.m3u8
            python3 twitch.py orestidatv > ../../streams/FlashTV.m3u8
            python3 twitch.py orthodoxiaradio > ../../streams/Orthodoxia_Radio_TV.m3u8          
            python3 twitch.py pronewstvgr > ../../streams/ProNews.m3u8
            python3 twitch.py tvkosmosgr > ../../streams/tvkosmosgr.m3u8
            python3 twitch.py topkozani24 > ../../streams/Top_Channel_Greece.m3u8
            python3 twitch.py xtvision > ../../streams/XTV.m3u8
            python3 twitch.py xtvision2 > ../../streams/XTV2.m3u8
            python3 twitch.py centerwebtv > ../../streams/centertv.m3u8
            python3 twitch.py thesslive01 > ../../streams/thessaliatv.m3u8
            python3 twitch.py starfmtvdramas > ../../streams/tvstarfm.m3u8
            python3 twitch.py iviewtvgr > ../../streams/iviewtvgr.m3u8
            python3 twitch.py xylagany_paradosi > ../../streams/xylagany_paradosi.m3u8
            python3 twitch.py alithiavideo > ../../streams/alithiatv.m3u8
            python3 twitch.py hotbeatstv > ../../streams/hotbeatstv.m3u8
            python3 twitch.py zefstv1 > ../../streams/plutontv.m3u8
            python3 twitch.py maron_tv > ../../streams/marontvgr.m3u8
            python3 twitch.py radiotvanemosgr > ../../streams/radiotvanemosgr.m3u8
            python3 twitch.py extacy_tv > ../../streams/extacytv.m3u8
            python3 twitch.py extacytvgreeks > ../../streams/extacytvgreeks.m3u8
            python3 twitch.py extacytvcinema > ../../streams/extacytvcinema.m3u8
            python3 twitch.py farostv1959 > ../../streams/farostvchurch.m3u8
      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git commit -m "streams updated"
          git push
